### ISSUE TITLE
Day 17 does not work for all inputs

### ISSUE THREAD

**Issue by nkiesel** [tginsberg/advent-2023-kotlin#1]
https://github.com/tginsberg/advent-2023-kotlin/blob/98b628bf2d5145adf02bf00ee2a002e21207c6fc/src/main/kotlin/com/ginsberg/advent2023/Day17.kt#L46

Hi, I struggled to find the correct solution for part 2.  I finally gave up and looked at your code. However, your code produced the same wrong result for my input. I then looked around a bit more and finally realized that for my input, the first step is going south and not east!  Thus, adding 2 starting steps to the queue solved the issue.
Thus, I would think you need to use something like 
```kotlin
listOf(EAST, SOUTH).map { State(Point2D(0, 0), it, 0) }.forEach {
    queue += Work(it, 0)
    seen += it
}
```

**Comment by tginsberg** [comment]
Hi @nkiesel! Thanks for letting me know. Somebody on Reddit pointed this out to me as well, but I haven't had time to create an input to make this fail yet. I think you're right though, adding two starting points (EAST and SOUTH) should work. Let me create an input and the change you've got here looks sensible.

Also, thanks for reading my solution and digging into it for a fix. I appreciate it very much!

**Comment by tginsberg** [comment]
Found an input that somebody left for me on Reddit and I missed. I coded up the fix slightly differently than what you had proposed but materially the same. I credited both of you on my blog, so thank you!
